name: Publish to Pypi

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-build:
    uses: ./.github/workflows/package.yml
  publish-to-pypi:
    needs: call-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Publish to Pypi
        run: |
          poetry publish
      
